export interface CityFact {
  emoji: string;
  text: string;
  type: "positive" | "negative" | "neutral";
}

export const CITY_FACTS: Record<string, CityFact[]> = {
  mumbai: [
    { emoji: "🚂", text: "Mumbai's local trains carry 7.5 million passengers daily — more than the population of 36 countries.", type: "neutral" },
    { emoji: "💰", text: "Mumbai contributes ~6.16% of India's GDP and handles 70% of the country's maritime trade.", type: "positive" },
    { emoji: "🎬", text: "Bollywood produces over 1,500 films a year — more than Hollywood.", type: "positive" },
    { emoji: "🌊", text: "Marine Drive's 'Queen's Necklace' view at night is one of the most iconic cityscapes in the world.", type: "positive" },
    { emoji: "🏠", text: "Mumbai's rent is among the highest globally — a parking spot in South Mumbai can cost more than an apartment in most Indian cities.", type: "negative" },
    { emoji: "🌧️", text: "Mumbai receives ~2,400mm of rain annually. The 2005 flood saw 944mm in a single day — a world record for a metro city.", type: "negative" },
    { emoji: "🚗", text: "Average Mumbaikar spends 1.5 hours commuting daily. The Andheri–Churchgate stretch is among the most crowded rail routes on Earth.", type: "negative" },
    { emoji: "🍽️", text: "Mumbai's street food scene — vada pav, pav bhaji, bhel puri — is available 24/7 and costs less than ₹50 a meal.", type: "positive" },
    { emoji: "🏗️", text: "Antilia, the world's most expensive private residence ($2B), is located in Mumbai — while 42% of the city lives in slums.", type: "neutral" },
    { emoji: "🌆", text: "Mumbai never sleeps — it's one of the only Indian cities where you can get a meal, a cab, or a haircut at 3 AM.", type: "positive" },
  ],
  delhi: [
    { emoji: "😷", text: "Delhi's winter AQI regularly crosses 400+ (severe). Breathing Delhi air in November equals smoking 15-20 cigarettes a day.", type: "negative" },
    { emoji: "🏛️", text: "Delhi has been the capital of multiple empires for over 1,000 years — it has the ruins of 7 historical cities within it.", type: "positive" },
    { emoji: "🚇", text: "Delhi Metro is the world's largest metro system by route length outside of China, covering 390+ km with 250+ stations.", type: "positive" },
    { emoji: "🍗", text: "Chandni Chowk has served food since the 1600s — some shops are 300+ years old. Paranthe Wali Gali alone has 30+ varieties.", type: "positive" },
    { emoji: "🌡️", text: "Delhi experiences extreme temperature swings — from 2°C in January to 48°C in June. That's a 46-degree annual range.", type: "negative" },
    { emoji: "🚗", text: "Delhi has more registered cars than Mumbai, Chennai, and Kolkata combined — over 1.2 crore vehicles on road.", type: "negative" },
    { emoji: "📚", text: "Delhi hosts the world's largest book fair, the Delhi Book Fair, attracting over 1 million visitors every year.", type: "positive" },
    { emoji: "💸", text: "Delhi's per capita income is the highest in India at ₹4.6 lakh — nearly double the national average.", type: "positive" },
    { emoji: "🌳", text: "Despite pollution, Delhi has more green cover (20%) than most Indian metros, thanks to the Ridge forest and Yamuna floodplains.", type: "neutral" },
    { emoji: "🥊", text: "Crime rate is a concern — Delhi reports the highest number of crimes among Indian cities, though policing has improved significantly.", type: "negative" },
  ],
  bangalore: [
    { emoji: "🚗", text: "Bangalore's traffic costs the city ₹38,000 crore annually. Average commuter wastes 1 hour 48 minutes daily in traffic.", type: "negative" },
    { emoji: "💻", text: "Bangalore contributes 38% of India's total IT exports and is home to 10,000+ startups — the most in India.", type: "positive" },
    { emoji: "🌤️", text: "Average temperature stays between 18-32°C year-round. Bangalore is one of the few Indian cities that rarely needs AC.", type: "positive" },
    { emoji: "☕", text: "Bangalore's café culture is legendary — it has more specialty coffee shops per capita than any Indian city. Filter coffee started here.", type: "positive" },
    { emoji: "🌊", text: "The city has lost 79% of its lakes in the last 50 years — from 262 lakes in 1960 to just 81 today.", type: "negative" },
    { emoji: "💰", text: "Startup unicorn density in Bangalore rivals Silicon Valley — Flipkart, Swiggy, Razorpay, and Zerodha all started here.", type: "positive" },
    { emoji: "🏗️", text: "Rent in Bangalore has surged 30-50% post-COVID as tech companies called employees back to office.", type: "negative" },
    { emoji: "🌳", text: "Known as the Garden City, Bangalore has 1,200+ parks including Cubbon Park (120 acres) and Lalbagh (240 acres).", type: "positive" },
    { emoji: "🍺", text: "Bangalore is India's pub capital — over 1,000 pubs and breweries serve the city's young, tech-savvy population.", type: "positive" },
    { emoji: "💧", text: "Bangalore faces a water crisis — the city relies on Cauvery river water pumped 100km away and 500m uphill.", type: "negative" },
  ],
  chennai: [
    { emoji: "🏖️", text: "Marina Beach is the longest urban beach in India (13 km) and the second longest in the world.", type: "positive" },
    { emoji: "🏥", text: "Chennai is India's healthcare capital — it attracts 40% of all medical tourists visiting India.", type: "positive" },
    { emoji: "🚗", text: "Tamil Nadu produces 35% of India's automobiles. Chennai is called the 'Detroit of India'.", type: "positive" },
    { emoji: "🌡️", text: "Chennai's summer heat (38-42°C) combined with 80%+ humidity makes it feel like 50°C. Not for the faint-hearted.", type: "negative" },
    { emoji: "💧", text: "Chennai faced 'Day Zero' in 2019 when all 4 reservoirs ran dry. Water tankers became a daily reality.", type: "negative" },
    { emoji: "🎵", text: "The Margazhi music season (Dec-Jan) is the world's largest cultural festival — 3,000+ Carnatic music concerts in 6 weeks.", type: "positive" },
    { emoji: "🍛", text: "A full South Indian meal (meals) costs ₹60-80 at a local mess — one of the cheapest nutritious meals in any metro.", type: "positive" },
    { emoji: "🌊", text: "The 2015 floods submerged 80% of the city, causing ₹20,000 crore in damage. Flood risk remains a concern.", type: "negative" },
    { emoji: "🎬", text: "Kollywood (Tamil cinema) produces 300+ films annually and Tamil Nadu has the highest number of cinema screens per capita.", type: "positive" },
    { emoji: "📱", text: "Chennai has the cheapest mobile data in India — and India already has the world's cheapest mobile data.", type: "positive" },
  ],
  hyderabad: [
    { emoji: "🍗", text: "Hyderabadi biryani is UNESCO-recognized as an intangible cultural heritage candidate. The city has 5,000+ biryani joints.", type: "positive" },
    { emoji: "💻", text: "HITEC City generates $5 billion+ in IT revenue. Microsoft, Google, Amazon, and Apple all have their largest India offices here.", type: "positive" },
    { emoji: "💰", text: "Hyderabad offers the best cost-to-salary ratio among Indian IT cities — high salaries with 30-40% lower rent than Bangalore.", type: "positive" },
    { emoji: "🏰", text: "The 400-year-old Charminar and Golconda Fort attract 10 million+ tourists annually.", type: "positive" },
    { emoji: "🌡️", text: "Summer temperatures hit 42-45°C in April-May. The dry heat is intense but more bearable than Chennai's humid heat.", type: "negative" },
    { emoji: "🚗", text: "Traffic on the Gachibowli–Madhapur stretch during peak hours adds 45 minutes to what should be a 15-minute drive.", type: "negative" },
    { emoji: "💊", text: "Hyderabad produces 40% of India's pharma output and is known as the 'Bulk Drug Capital of India'.", type: "positive" },
    { emoji: "🏗️", text: "New metro, ORR, and flyovers have transformed connectivity, but construction disruptions are constant.", type: "neutral" },
    { emoji: "🍽️", text: "Irani chai + Osmania biscuit costs ₹30 — a 100-year-old tradition still going strong in every Irani café.", type: "positive" },
    { emoji: "💧", text: "Hussain Sagar lake, once a scenic landmark, is now one of the most polluted water bodies in India.", type: "negative" },
  ],
  pune: [
    { emoji: "📚", text: "Pune has 800+ educational institutions and is called 'Oxford of the East'. Student population exceeds 10 lakh.", type: "positive" },
    { emoji: "🌤️", text: "Pune's weather is near-perfect — 20-33°C most of the year. Monsoons are beautiful, winters are mild.", type: "positive" },
    { emoji: "🏍️", text: "Pune is the two-wheeler capital of India — it has more two-wheelers per capita than any other city.", type: "neutral" },
    { emoji: "🚗", text: "The Pune-Mumbai Expressway (94.5 km) is one of India's busiest and most accident-prone highways.", type: "negative" },
    { emoji: "💻", text: "Hinjewadi IT Park alone houses 300+ companies. Pune's IT sector employs 5 lakh+ professionals.", type: "positive" },
    { emoji: "🍽️", text: "Pune's food scene ranges from ₹30 misal pav to world-class restaurants. FC Road and Koregaon Park are foodie havens.", type: "positive" },
    { emoji: "🏠", text: "Rent has doubled in areas like Hinjewadi and Kharadi in the last 5 years due to IT boom.", type: "negative" },
    { emoji: "🌳", text: "Pune has the Sahyadri hills at its doorstep — Lonavala, Lavasa, and 50+ forts are within a 2-hour drive.", type: "positive" },
    { emoji: "🚌", text: "PMPML buses are notoriously unreliable. Pune's public transport lags far behind Delhi and Mumbai.", type: "negative" },
    { emoji: "🍺", text: "Pune's German Bakery, Koregaon Park nightlife, and craft beer scene make it one of India's most fun cities for young professionals.", type: "positive" },
  ],
  kolkata: [
    { emoji: "💰", text: "Kolkata is India's most affordable metro — you can eat a full meal for ₹40, take a bus for ₹7, and live well on ₹20K/month.", type: "positive" },
    { emoji: "🚋", text: "Kolkata is the only Indian city with a tram network (since 1902) and India's oldest operating metro (since 1984).", type: "positive" },
    { emoji: "📚", text: "College Street has the largest second-hand book market in the world, stretching over 1.5 km.", type: "positive" },
    { emoji: "🍛", text: "Street food capital — kathi rolls, puchka (pani puri), jhalmuri, and ₹20 egg rolls are available every 50 meters.", type: "positive" },
    { emoji: "💼", text: "Kolkata's IT sector is growing but salaries are 20-30% lower than Bangalore/Hyderabad for similar roles.", type: "negative" },
    { emoji: "🏗️", text: "Infrastructure development is slow — many roads flood during moderate rain, and traffic management is poor.", type: "negative" },
    { emoji: "🎭", text: "Durga Puja is a ₹40,000 crore economy. The 5-day festival transforms the entire city into an open-air art gallery.", type: "positive" },
    { emoji: "🌡️", text: "Kolkata's summers (35-40°C with 90%+ humidity) are brutal. The 'feels like' temperature often crosses 50°C.", type: "negative" },
    { emoji: "☕", text: "Kolkata's adda (chat) culture at Coffee House and street-side chai stalls has produced Nobel laureates and revolutionaries.", type: "positive" },
    { emoji: "🏠", text: "The only metro where a decent 2BHK in the city centre costs under ₹25,000 — unheard of in Mumbai or Bangalore.", type: "positive" },
  ],
  ahmedabad: [
    { emoji: "🏛️", text: "Ahmedabad was India's first UNESCO World Heritage City (2017) — its pol (neighborhood) architecture dates back 600 years.", type: "positive" },
    { emoji: "🚫", text: "Gujarat has complete prohibition — no alcohol is legally available. Some see this as positive, many find it limiting.", type: "neutral" },
    { emoji: "🍽️", text: "Ahmedabad's vegetarian food scene is world-class. The city has the most diverse veg street food in India.", type: "positive" },
    { emoji: "🌡️", text: "Summer temperatures reach 45-48°C. Ahmedabad recorded 51°C in 2016, one of the highest in Indian urban history.", type: "negative" },
    { emoji: "💰", text: "Cost of living is 35-40% cheaper than Mumbai while salaries in textiles and pharma are competitive.", type: "positive" },
    { emoji: "🏗️", text: "The Sabarmati Riverfront project transformed 11 km of neglected riverbank into one of India's finest public spaces.", type: "positive" },
    { emoji: "🚗", text: "Ahmedabad's BRTS (Bus Rapid Transit System) was India's first and is one of the most efficient public transport systems.", type: "positive" },
    { emoji: "💧", text: "Water scarcity is a growing concern — the Sabarmati river is essentially dry for most of the year.", type: "negative" },
    { emoji: "🏭", text: "Air quality dips during winter months due to industrial pollution from the nearby Vatva-Narol industrial belt.", type: "negative" },
    { emoji: "📈", text: "Gujarat's ease of doing business ranking is #1 in India — Ahmedabad benefits from a strong entrepreneurial culture.", type: "positive" },
  ],
  jaipur: [
    { emoji: "🏰", text: "The Pink City was planned in 1727 by Maharaja Jai Singh II — one of the world's earliest planned cities.", type: "positive" },
    { emoji: "💰", text: "Jaipur is one of the cheapest state capitals to live in. A comfortable lifestyle costs 50% less than Mumbai.", type: "positive" },
    { emoji: "💎", text: "Jaipur processes 90% of the world's gemstones. The Johari Bazaar gem trade is worth ₹50,000 crore annually.", type: "positive" },
    { emoji: "🌡️", text: "Jaipur's summers are scorching — 44-47°C in May-June. Desert proximity means extremely dry heat.", type: "negative" },
    { emoji: "🏗️", text: "IT infrastructure is growing but still nascent. Job options are limited compared to Bangalore or Hyderabad.", type: "negative" },
    { emoji: "🚗", text: "Traffic in the old city (walled area) is chaotic — narrow lanes designed for horses now handle cars and trucks.", type: "negative" },
    { emoji: "📸", text: "Jaipur is India's most Instagrammed city — Hawa Mahal alone gets 5 million+ visitor photos annually.", type: "positive" },
    { emoji: "🍽️", text: "Dal baati churma, pyaaz ki kachori, and lassi are incredibly cheap — a full Rajasthani thali costs ₹80-100.", type: "positive" },
    { emoji: "🚇", text: "Jaipur Metro and new ring roads have improved connectivity, but public transport coverage is still sparse.", type: "neutral" },
    { emoji: "🐪", text: "You can still see camels on city roads during festivals. The Camel Festival in January is a unique spectacle.", type: "positive" },
  ],
  lucknow: [
    { emoji: "🍗", text: "Lucknow's kebabs are legendary. Tunday Kababi has been serving ₹30 kebabs with 160 spices since 1905 — 120 years.", type: "positive" },
    { emoji: "💰", text: "Lucknow is one of India's cheapest cities — a family of 4 can live comfortably on ₹40,000/month including rent.", type: "positive" },
    { emoji: "🏛️", text: "The Bara Imambara has a maze (Bhool Bhulaiya) that's the largest in India — 1,024 pathways with no dead ends.", type: "positive" },
    { emoji: "🚗", text: "Traffic is growing chaotic as the city expands. Gomti Nagar to Hazratganj (7 km) can take 45 minutes in peak hours.", type: "negative" },
    { emoji: "💼", text: "Job market is limited — most high-paying roles are government or real estate. IT sector is still in its infancy.", type: "negative" },
    { emoji: "🏗️", text: "Lucknow Metro, new expressways, and the IT City project are transforming the city's infrastructure rapidly.", type: "positive" },
    { emoji: "🎭", text: "Lucknow's 'tehzeeb' (etiquette) is famous — it's possibly the politest city in India.", type: "positive" },
    { emoji: "🌡️", text: "Summers hit 45°C+ and winters drop to 3-4°C. The annual temperature range of 40+ degrees is among India's highest.", type: "negative" },
    { emoji: "🍽️", text: "A full Awadhi meal (biryani, kebab, roomali roti, sheermal) costs ₹150 — what you'd pay for a single dish in Mumbai.", type: "positive" },
    { emoji: "💧", text: "The Gomti river is heavily polluted — untreated sewage from 20+ drains flows directly into it.", type: "negative" },
  ],
};

export function getCityFacts(slug: string): CityFact[] {
  return CITY_FACTS[slug] || [];
}
