import { CityData, PriceItem } from "./types";
import { additionalCities } from "./moreCities";

// Helper to create price items for a city
function createPrices(values: Record<string, number>): PriceItem[] {
  return PRICE_TEMPLATE.map((template) => ({
    ...template,
    price: values[template.item] ?? 0,
  }));
}

// Master template of all items tracked
const PRICE_TEMPLATE: Omit<PriceItem, "price">[] = [
  // Restaurants & Dining
  { category: "Restaurants & Dining", item: "Veg Thali (local restaurant)", unit: "per plate" },
  { category: "Restaurants & Dining", item: "Non-Veg Thali (local restaurant)", unit: "per plate" },
  { category: "Restaurants & Dining", item: "Meal for Two (high-end restaurant)", unit: "per meal" },
  { category: "Restaurants & Dining", item: "Chai (regular cup)", unit: "per cup" },
  { category: "Restaurants & Dining", item: "Coffee (Cappuccino)", unit: "per cup" },
  { category: "Restaurants & Dining", item: "Street Food (Vada Pav / Samosa)", unit: "per piece" },
  { category: "Restaurants & Dining", item: "Biryani (chicken)", unit: "per plate" },
  { category: "Restaurants & Dining", item: "Dosa (plain)", unit: "per plate" },
  { category: "Restaurants & Dining", item: "Fast Food Combo (McDonald's)", unit: "per meal" },
  { category: "Restaurants & Dining", item: "Soft Drink (Coca-Cola, 300ml)", unit: "per bottle" },
  { category: "Restaurants & Dining", item: "Bottled Water (1 litre)", unit: "per bottle" },

  // Groceries
  { category: "Groceries", item: "Rice (Basmati)", unit: "1 kg" },
  { category: "Groceries", item: "Wheat Flour (Atta)", unit: "1 kg" },
  { category: "Groceries", item: "Toor Dal", unit: "1 kg" },
  { category: "Groceries", item: "Milk (Full Cream)", unit: "1 litre" },
  { category: "Groceries", item: "Eggs", unit: "12 pcs" },
  { category: "Groceries", item: "Chicken", unit: "1 kg" },
  { category: "Groceries", item: "Paneer", unit: "1 kg" },
  { category: "Groceries", item: "Onions", unit: "1 kg" },
  { category: "Groceries", item: "Tomatoes", unit: "1 kg" },
  { category: "Groceries", item: "Potatoes", unit: "1 kg" },
  { category: "Groceries", item: "Cooking Oil (Sunflower)", unit: "1 litre" },
  { category: "Groceries", item: "Sugar", unit: "1 kg" },
  { category: "Groceries", item: "Apples (Shimla)", unit: "1 kg" },
  { category: "Groceries", item: "Bananas", unit: "1 dozen" },
  { category: "Groceries", item: "Bread (White, Sliced)", unit: "1 loaf" },

  // Transportation
  { category: "Transportation", item: "Auto Rickshaw (minimum fare)", unit: "per ride" },
  { category: "Transportation", item: "Auto Rickshaw (per km after min)", unit: "per km" },
  { category: "Transportation", item: "Metro / Local Train (monthly pass)", unit: "per month" },
  { category: "Transportation", item: "Bus (monthly pass)", unit: "per month" },
  { category: "Transportation", item: "Ola/Uber Mini (per km)", unit: "per km" },
  { category: "Transportation", item: "Petrol", unit: "1 litre" },
  { category: "Transportation", item: "Diesel", unit: "1 litre" },
  { category: "Transportation", item: "Honda Activa (new)", unit: "on-road price" },
  { category: "Transportation", item: "Maruti Swift (base model, new)", unit: "on-road price" },

  // Utilities (Monthly)
  { category: "Utilities (Monthly)", item: "Electricity (2BHK, avg usage)", unit: "per month" },
  { category: "Utilities (Monthly)", item: "Water Bill", unit: "per month" },
  { category: "Utilities (Monthly)", item: "Cooking Gas (LPG Cylinder)", unit: "per cylinder" },
  { category: "Utilities (Monthly)", item: "Broadband Internet (100 Mbps)", unit: "per month" },
  { category: "Utilities (Monthly)", item: "Mobile Plan (Jio/Airtel, 2GB/day)", unit: "per month" },

  // Accommodation - Rent
  { category: "Accommodation - Rent (Monthly)", item: "1 BHK in City Centre", unit: "per month" },
  { category: "Accommodation - Rent (Monthly)", item: "1 BHK Outside City Centre", unit: "per month" },
  { category: "Accommodation - Rent (Monthly)", item: "2 BHK in City Centre", unit: "per month" },
  { category: "Accommodation - Rent (Monthly)", item: "2 BHK Outside City Centre", unit: "per month" },
  { category: "Accommodation - Rent (Monthly)", item: "3 BHK in City Centre", unit: "per month" },
  { category: "Accommodation - Rent (Monthly)", item: "3 BHK Outside City Centre", unit: "per month" },

  // PG / Shared Accommodation
  { category: "PG / Shared Accommodation (Monthly)", item: "PG - Private Room (with meals)", unit: "per month" },
  { category: "PG / Shared Accommodation (Monthly)", item: "PG - Private Room (without meals)", unit: "per month" },
  { category: "PG / Shared Accommodation (Monthly)", item: "PG - Double Sharing (with meals)", unit: "per month" },
  { category: "PG / Shared Accommodation (Monthly)", item: "PG - Double Sharing (without meals)", unit: "per month" },
  { category: "PG / Shared Accommodation (Monthly)", item: "PG - Triple Sharing (with meals)", unit: "per month" },
  { category: "PG / Shared Accommodation (Monthly)", item: "PG - Triple Sharing (without meals)", unit: "per month" },

  // Lifestyle & Entertainment
  { category: "Lifestyle & Entertainment", item: "Gym Membership", unit: "per month" },
  { category: "Lifestyle & Entertainment", item: "Movie Ticket (Multiplex)", unit: "per ticket" },
  { category: "Lifestyle & Entertainment", item: "Netflix (Standard Plan)", unit: "per month" },
  { category: "Lifestyle & Entertainment", item: "Spotify Premium", unit: "per month" },
  { category: "Lifestyle & Entertainment", item: "Haircut (Men, basic salon)", unit: "per cut" },
  { category: "Lifestyle & Entertainment", item: "Domestic Beer (pint, restaurant)", unit: "per pint" },
  { category: "Lifestyle & Entertainment", item: "Imported Beer (bottle, restaurant)", unit: "per bottle" },
];

// ============================================================
// CITY DATA - 10 Major Indian Cities
// Prices in INR, as of early 2026
// ============================================================

const mumbaiPrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 150,
  "Non-Veg Thali (local restaurant)": 220,
  "Meal for Two (high-end restaurant)": 1800,
  "Chai (regular cup)": 15,
  "Coffee (Cappuccino)": 200,
  "Street Food (Vada Pav / Samosa)": 20,
  "Biryani (chicken)": 250,
  "Dosa (plain)": 80,
  "Fast Food Combo (McDonald's)": 250,
  "Soft Drink (Coca-Cola, 300ml)": 40,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 110,
  "Wheat Flour (Atta)": 55,
  "Toor Dal": 160,
  "Milk (Full Cream)": 62,
  "Eggs": 84,
  "Chicken": 280,
  "Paneer": 400,
  "Onions": 40,
  "Tomatoes": 50,
  "Potatoes": 35,
  "Cooking Oil (Sunflower)": 160,
  "Sugar": 48,
  "Apples (Shimla)": 200,
  "Bananas": 60,
  "Bread (White, Sliced)": 50,
  "Auto Rickshaw (minimum fare)": 23,
  "Auto Rickshaw (per km after min)": 16,
  "Metro / Local Train (monthly pass)": 1500,
  "Bus (monthly pass)": 900,
  "Ola/Uber Mini (per km)": 14,
  "Petrol": 105,
  "Diesel": 92,
  "Honda Activa (new)": 85000,
  "Maruti Swift (base model, new)": 700000,
  "Electricity (2BHK, avg usage)": 2500,
  "Water Bill": 500,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 800,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 35000,
  "1 BHK Outside City Centre": 18000,
  "2 BHK in City Centre": 60000,
  "2 BHK Outside City Centre": 30000,
  "3 BHK in City Centre": 95000,
  "3 BHK Outside City Centre": 45000,
  "PG - Private Room (with meals)": 18000,
  "PG - Private Room (without meals)": 14000,
  "PG - Double Sharing (with meals)": 12000,
  "PG - Double Sharing (without meals)": 9000,
  "PG - Triple Sharing (with meals)": 9000,
  "PG - Triple Sharing (without meals)": 7000,
  "Gym Membership": 2500,
  "Movie Ticket (Multiplex)": 300,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 200,
  "Domestic Beer (pint, restaurant)": 250,
  "Imported Beer (bottle, restaurant)": 450,
};

const delhiPrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 120,
  "Non-Veg Thali (local restaurant)": 200,
  "Meal for Two (high-end restaurant)": 1600,
  "Chai (regular cup)": 15,
  "Coffee (Cappuccino)": 190,
  "Street Food (Vada Pav / Samosa)": 15,
  "Biryani (chicken)": 220,
  "Dosa (plain)": 70,
  "Fast Food Combo (McDonald's)": 250,
  "Soft Drink (Coca-Cola, 300ml)": 40,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 100,
  "Wheat Flour (Atta)": 50,
  "Toor Dal": 155,
  "Milk (Full Cream)": 60,
  "Eggs": 78,
  "Chicken": 250,
  "Paneer": 380,
  "Onions": 35,
  "Tomatoes": 45,
  "Potatoes": 30,
  "Cooking Oil (Sunflower)": 155,
  "Sugar": 46,
  "Apples (Shimla)": 180,
  "Bananas": 50,
  "Bread (White, Sliced)": 45,
  "Auto Rickshaw (minimum fare)": 25,
  "Auto Rickshaw (per km after min)": 11,
  "Metro / Local Train (monthly pass)": 1250,
  "Bus (monthly pass)": 800,
  "Ola/Uber Mini (per km)": 12,
  "Petrol": 95,
  "Diesel": 88,
  "Honda Activa (new)": 82000,
  "Maruti Swift (base model, new)": 680000,
  "Electricity (2BHK, avg usage)": 2200,
  "Water Bill": 400,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 750,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 22000,
  "1 BHK Outside City Centre": 12000,
  "2 BHK in City Centre": 40000,
  "2 BHK Outside City Centre": 22000,
  "3 BHK in City Centre": 70000,
  "3 BHK Outside City Centre": 35000,
  "PG - Private Room (with meals)": 15000,
  "PG - Private Room (without meals)": 11000,
  "PG - Double Sharing (with meals)": 10000,
  "PG - Double Sharing (without meals)": 7500,
  "PG - Triple Sharing (with meals)": 7500,
  "PG - Triple Sharing (without meals)": 5500,
  "Gym Membership": 2000,
  "Movie Ticket (Multiplex)": 280,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 150,
  "Domestic Beer (pint, restaurant)": 220,
  "Imported Beer (bottle, restaurant)": 400,
};

const bangalorePrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 130,
  "Non-Veg Thali (local restaurant)": 200,
  "Meal for Two (high-end restaurant)": 1500,
  "Chai (regular cup)": 15,
  "Coffee (Cappuccino)": 200,
  "Street Food (Vada Pav / Samosa)": 20,
  "Biryani (chicken)": 220,
  "Dosa (plain)": 60,
  "Fast Food Combo (McDonald's)": 250,
  "Soft Drink (Coca-Cola, 300ml)": 40,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 105,
  "Wheat Flour (Atta)": 52,
  "Toor Dal": 155,
  "Milk (Full Cream)": 56,
  "Eggs": 78,
  "Chicken": 240,
  "Paneer": 380,
  "Onions": 38,
  "Tomatoes": 45,
  "Potatoes": 35,
  "Cooking Oil (Sunflower)": 155,
  "Sugar": 46,
  "Apples (Shimla)": 200,
  "Bananas": 50,
  "Bread (White, Sliced)": 45,
  "Auto Rickshaw (minimum fare)": 30,
  "Auto Rickshaw (per km after min)": 15,
  "Metro / Local Train (monthly pass)": 1400,
  "Bus (monthly pass)": 1350,
  "Ola/Uber Mini (per km)": 13,
  "Petrol": 103,
  "Diesel": 88,
  "Honda Activa (new)": 84000,
  "Maruti Swift (base model, new)": 690000,
  "Electricity (2BHK, avg usage)": 2000,
  "Water Bill": 350,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 750,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 25000,
  "1 BHK Outside City Centre": 14000,
  "2 BHK in City Centre": 45000,
  "2 BHK Outside City Centre": 25000,
  "3 BHK in City Centre": 75000,
  "3 BHK Outside City Centre": 38000,
  "PG - Private Room (with meals)": 16000,
  "PG - Private Room (without meals)": 12000,
  "PG - Double Sharing (with meals)": 11000,
  "PG - Double Sharing (without meals)": 8000,
  "PG - Triple Sharing (with meals)": 8000,
  "PG - Triple Sharing (without meals)": 6000,
  "Gym Membership": 2200,
  "Movie Ticket (Multiplex)": 250,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 150,
  "Domestic Beer (pint, restaurant)": 230,
  "Imported Beer (bottle, restaurant)": 420,
};

const chennaiPrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 100,
  "Non-Veg Thali (local restaurant)": 170,
  "Meal for Two (high-end restaurant)": 1300,
  "Chai (regular cup)": 12,
  "Coffee (Cappuccino)": 180,
  "Street Food (Vada Pav / Samosa)": 15,
  "Biryani (chicken)": 200,
  "Dosa (plain)": 50,
  "Fast Food Combo (McDonald's)": 250,
  "Soft Drink (Coca-Cola, 300ml)": 40,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 95,
  "Wheat Flour (Atta)": 50,
  "Toor Dal": 150,
  "Milk (Full Cream)": 52,
  "Eggs": 72,
  "Chicken": 220,
  "Paneer": 360,
  "Onions": 35,
  "Tomatoes": 40,
  "Potatoes": 32,
  "Cooking Oil (Sunflower)": 150,
  "Sugar": 44,
  "Apples (Shimla)": 220,
  "Bananas": 45,
  "Bread (White, Sliced)": 42,
  "Auto Rickshaw (minimum fare)": 25,
  "Auto Rickshaw (per km after min)": 12,
  "Metro / Local Train (monthly pass)": 1200,
  "Bus (monthly pass)": 750,
  "Ola/Uber Mini (per km)": 12,
  "Petrol": 103,
  "Diesel": 90,
  "Honda Activa (new)": 83000,
  "Maruti Swift (base model, new)": 685000,
  "Electricity (2BHK, avg usage)": 1800,
  "Water Bill": 300,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 700,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 18000,
  "1 BHK Outside City Centre": 10000,
  "2 BHK in City Centre": 32000,
  "2 BHK Outside City Centre": 18000,
  "3 BHK in City Centre": 55000,
  "3 BHK Outside City Centre": 28000,
  "PG - Private Room (with meals)": 12000,
  "PG - Private Room (without meals)": 9000,
  "PG - Double Sharing (with meals)": 8500,
  "PG - Double Sharing (without meals)": 6500,
  "PG - Triple Sharing (with meals)": 6500,
  "PG - Triple Sharing (without meals)": 5000,
  "Gym Membership": 1800,
  "Movie Ticket (Multiplex)": 200,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 120,
  "Domestic Beer (pint, restaurant)": 200,
  "Imported Beer (bottle, restaurant)": 380,
};

const hyderabadPrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 100,
  "Non-Veg Thali (local restaurant)": 170,
  "Meal for Two (high-end restaurant)": 1200,
  "Chai (regular cup)": 12,
  "Coffee (Cappuccino)": 175,
  "Street Food (Vada Pav / Samosa)": 15,
  "Biryani (chicken)": 180,
  "Dosa (plain)": 55,
  "Fast Food Combo (McDonald's)": 250,
  "Soft Drink (Coca-Cola, 300ml)": 40,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 95,
  "Wheat Flour (Atta)": 48,
  "Toor Dal": 148,
  "Milk (Full Cream)": 54,
  "Eggs": 72,
  "Chicken": 220,
  "Paneer": 360,
  "Onions": 32,
  "Tomatoes": 38,
  "Potatoes": 30,
  "Cooking Oil (Sunflower)": 150,
  "Sugar": 44,
  "Apples (Shimla)": 210,
  "Bananas": 45,
  "Bread (White, Sliced)": 42,
  "Auto Rickshaw (minimum fare)": 25,
  "Auto Rickshaw (per km after min)": 12,
  "Metro / Local Train (monthly pass)": 1100,
  "Bus (monthly pass)": 700,
  "Ola/Uber Mini (per km)": 11,
  "Petrol": 109,
  "Diesel": 97,
  "Honda Activa (new)": 82000,
  "Maruti Swift (base model, new)": 680000,
  "Electricity (2BHK, avg usage)": 1700,
  "Water Bill": 300,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 700,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 16000,
  "1 BHK Outside City Centre": 9000,
  "2 BHK in City Centre": 28000,
  "2 BHK Outside City Centre": 16000,
  "3 BHK in City Centre": 50000,
  "3 BHK Outside City Centre": 26000,
  "PG - Private Room (with meals)": 12000,
  "PG - Private Room (without meals)": 9000,
  "PG - Double Sharing (with meals)": 8000,
  "PG - Double Sharing (without meals)": 6000,
  "PG - Triple Sharing (with meals)": 6000,
  "PG - Triple Sharing (without meals)": 4500,
  "Gym Membership": 1500,
  "Movie Ticket (Multiplex)": 200,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 120,
  "Domestic Beer (pint, restaurant)": 200,
  "Imported Beer (bottle, restaurant)": 380,
};

const punePrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 120,
  "Non-Veg Thali (local restaurant)": 180,
  "Meal for Two (high-end restaurant)": 1400,
  "Chai (regular cup)": 15,
  "Coffee (Cappuccino)": 180,
  "Street Food (Vada Pav / Samosa)": 15,
  "Biryani (chicken)": 200,
  "Dosa (plain)": 65,
  "Fast Food Combo (McDonald's)": 250,
  "Soft Drink (Coca-Cola, 300ml)": 40,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 100,
  "Wheat Flour (Atta)": 50,
  "Toor Dal": 155,
  "Milk (Full Cream)": 56,
  "Eggs": 78,
  "Chicken": 240,
  "Paneer": 370,
  "Onions": 35,
  "Tomatoes": 42,
  "Potatoes": 32,
  "Cooking Oil (Sunflower)": 155,
  "Sugar": 46,
  "Apples (Shimla)": 190,
  "Bananas": 50,
  "Bread (White, Sliced)": 45,
  "Auto Rickshaw (minimum fare)": 23,
  "Auto Rickshaw (per km after min)": 14,
  "Metro / Local Train (monthly pass)": 1100,
  "Bus (monthly pass)": 700,
  "Ola/Uber Mini (per km)": 12,
  "Petrol": 105,
  "Diesel": 90,
  "Honda Activa (new)": 83000,
  "Maruti Swift (base model, new)": 685000,
  "Electricity (2BHK, avg usage)": 1800,
  "Water Bill": 350,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 750,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 20000,
  "1 BHK Outside City Centre": 12000,
  "2 BHK in City Centre": 35000,
  "2 BHK Outside City Centre": 20000,
  "3 BHK in City Centre": 55000,
  "3 BHK Outside City Centre": 30000,
  "PG - Private Room (with meals)": 14000,
  "PG - Private Room (without meals)": 10000,
  "PG - Double Sharing (with meals)": 9500,
  "PG - Double Sharing (without meals)": 7000,
  "PG - Triple Sharing (with meals)": 7000,
  "PG - Triple Sharing (without meals)": 5000,
  "Gym Membership": 1800,
  "Movie Ticket (Multiplex)": 250,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 130,
  "Domestic Beer (pint, restaurant)": 200,
  "Imported Beer (bottle, restaurant)": 380,
};

const kolkataPrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 90,
  "Non-Veg Thali (local restaurant)": 150,
  "Meal for Two (high-end restaurant)": 1100,
  "Chai (regular cup)": 10,
  "Coffee (Cappuccino)": 170,
  "Street Food (Vada Pav / Samosa)": 12,
  "Biryani (chicken)": 180,
  "Dosa (plain)": 55,
  "Fast Food Combo (McDonald's)": 240,
  "Soft Drink (Coca-Cola, 300ml)": 35,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 90,
  "Wheat Flour (Atta)": 45,
  "Toor Dal": 145,
  "Milk (Full Cream)": 52,
  "Eggs": 72,
  "Chicken": 220,
  "Paneer": 340,
  "Onions": 30,
  "Tomatoes": 38,
  "Potatoes": 25,
  "Cooking Oil (Sunflower)": 148,
  "Sugar": 43,
  "Apples (Shimla)": 200,
  "Bananas": 45,
  "Bread (White, Sliced)": 40,
  "Auto Rickshaw (minimum fare)": 25,
  "Auto Rickshaw (per km after min)": 12,
  "Metro / Local Train (monthly pass)": 800,
  "Bus (monthly pass)": 600,
  "Ola/Uber Mini (per km)": 10,
  "Petrol": 105,
  "Diesel": 90,
  "Honda Activa (new)": 81000,
  "Maruti Swift (base model, new)": 675000,
  "Electricity (2BHK, avg usage)": 1500,
  "Water Bill": 250,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 650,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 14000,
  "1 BHK Outside City Centre": 7500,
  "2 BHK in City Centre": 25000,
  "2 BHK Outside City Centre": 13000,
  "3 BHK in City Centre": 42000,
  "3 BHK Outside City Centre": 22000,
  "PG - Private Room (with meals)": 10000,
  "PG - Private Room (without meals)": 7500,
  "PG - Double Sharing (with meals)": 7000,
  "PG - Double Sharing (without meals)": 5000,
  "PG - Triple Sharing (with meals)": 5500,
  "PG - Triple Sharing (without meals)": 4000,
  "Gym Membership": 1200,
  "Movie Ticket (Multiplex)": 200,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 100,
  "Domestic Beer (pint, restaurant)": 180,
  "Imported Beer (bottle, restaurant)": 350,
};

const ahmedabadPrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 90,
  "Non-Veg Thali (local restaurant)": 160,
  "Meal for Two (high-end restaurant)": 1100,
  "Chai (regular cup)": 12,
  "Coffee (Cappuccino)": 170,
  "Street Food (Vada Pav / Samosa)": 15,
  "Biryani (chicken)": 180,
  "Dosa (plain)": 60,
  "Fast Food Combo (McDonald's)": 240,
  "Soft Drink (Coca-Cola, 300ml)": 35,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 95,
  "Wheat Flour (Atta)": 48,
  "Toor Dal": 148,
  "Milk (Full Cream)": 56,
  "Eggs": 75,
  "Chicken": 230,
  "Paneer": 350,
  "Onions": 30,
  "Tomatoes": 38,
  "Potatoes": 28,
  "Cooking Oil (Sunflower)": 148,
  "Sugar": 44,
  "Apples (Shimla)": 195,
  "Bananas": 45,
  "Bread (White, Sliced)": 42,
  "Auto Rickshaw (minimum fare)": 20,
  "Auto Rickshaw (per km after min)": 12,
  "Metro / Local Train (monthly pass)": 1000,
  "Bus (monthly pass)": 600,
  "Ola/Uber Mini (per km)": 10,
  "Petrol": 95,
  "Diesel": 88,
  "Honda Activa (new)": 81000,
  "Maruti Swift (base model, new)": 675000,
  "Electricity (2BHK, avg usage)": 1600,
  "Water Bill": 250,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 650,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 14000,
  "1 BHK Outside City Centre": 8000,
  "2 BHK in City Centre": 24000,
  "2 BHK Outside City Centre": 14000,
  "3 BHK in City Centre": 40000,
  "3 BHK Outside City Centre": 22000,
  "PG - Private Room (with meals)": 10000,
  "PG - Private Room (without meals)": 7500,
  "PG - Double Sharing (with meals)": 7000,
  "PG - Double Sharing (without meals)": 5000,
  "PG - Triple Sharing (with meals)": 5500,
  "PG - Triple Sharing (without meals)": 3800,
  "Gym Membership": 1200,
  "Movie Ticket (Multiplex)": 200,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 100,
  "Domestic Beer (pint, restaurant)": 180,
  "Imported Beer (bottle, restaurant)": 350,
};

const jaipurPrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 80,
  "Non-Veg Thali (local restaurant)": 150,
  "Meal for Two (high-end restaurant)": 1000,
  "Chai (regular cup)": 10,
  "Coffee (Cappuccino)": 160,
  "Street Food (Vada Pav / Samosa)": 12,
  "Biryani (chicken)": 170,
  "Dosa (plain)": 55,
  "Fast Food Combo (McDonald's)": 240,
  "Soft Drink (Coca-Cola, 300ml)": 35,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 90,
  "Wheat Flour (Atta)": 45,
  "Toor Dal": 145,
  "Milk (Full Cream)": 54,
  "Eggs": 72,
  "Chicken": 220,
  "Paneer": 340,
  "Onions": 28,
  "Tomatoes": 35,
  "Potatoes": 25,
  "Cooking Oil (Sunflower)": 145,
  "Sugar": 42,
  "Apples (Shimla)": 180,
  "Bananas": 40,
  "Bread (White, Sliced)": 40,
  "Auto Rickshaw (minimum fare)": 20,
  "Auto Rickshaw (per km after min)": 10,
  "Metro / Local Train (monthly pass)": 900,
  "Bus (monthly pass)": 550,
  "Ola/Uber Mini (per km)": 10,
  "Petrol": 100,
  "Diesel": 90,
  "Honda Activa (new)": 80000,
  "Maruti Swift (base model, new)": 670000,
  "Electricity (2BHK, avg usage)": 1500,
  "Water Bill": 200,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 600,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 12000,
  "1 BHK Outside City Centre": 7000,
  "2 BHK in City Centre": 20000,
  "2 BHK Outside City Centre": 12000,
  "3 BHK in City Centre": 35000,
  "3 BHK Outside City Centre": 18000,
  "PG - Private Room (with meals)": 9000,
  "PG - Private Room (without meals)": 6500,
  "PG - Double Sharing (with meals)": 6500,
  "PG - Double Sharing (without meals)": 4500,
  "PG - Triple Sharing (with meals)": 5000,
  "PG - Triple Sharing (without meals)": 3500,
  "Gym Membership": 1000,
  "Movie Ticket (Multiplex)": 180,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 80,
  "Domestic Beer (pint, restaurant)": 170,
  "Imported Beer (bottle, restaurant)": 350,
};

const lucknowPrices: Record<string, number> = {
  "Veg Thali (local restaurant)": 80,
  "Non-Veg Thali (local restaurant)": 140,
  "Meal for Two (high-end restaurant)": 1000,
  "Chai (regular cup)": 10,
  "Coffee (Cappuccino)": 150,
  "Street Food (Vada Pav / Samosa)": 10,
  "Biryani (chicken)": 160,
  "Dosa (plain)": 55,
  "Fast Food Combo (McDonald's)": 230,
  "Soft Drink (Coca-Cola, 300ml)": 35,
  "Bottled Water (1 litre)": 20,
  "Rice (Basmati)": 85,
  "Wheat Flour (Atta)": 42,
  "Toor Dal": 140,
  "Milk (Full Cream)": 52,
  "Eggs": 70,
  "Chicken": 200,
  "Paneer": 330,
  "Onions": 28,
  "Tomatoes": 32,
  "Potatoes": 22,
  "Cooking Oil (Sunflower)": 142,
  "Sugar": 42,
  "Apples (Shimla)": 180,
  "Bananas": 40,
  "Bread (White, Sliced)": 38,
  "Auto Rickshaw (minimum fare)": 20,
  "Auto Rickshaw (per km after min)": 10,
  "Metro / Local Train (monthly pass)": 850,
  "Bus (monthly pass)": 500,
  "Ola/Uber Mini (per km)": 9,
  "Petrol": 95,
  "Diesel": 88,
  "Honda Activa (new)": 80000,
  "Maruti Swift (base model, new)": 665000,
  "Electricity (2BHK, avg usage)": 1400,
  "Water Bill": 200,
  "Cooking Gas (LPG Cylinder)": 803,
  "Broadband Internet (100 Mbps)": 600,
  "Mobile Plan (Jio/Airtel, 2GB/day)": 299,
  "1 BHK in City Centre": 10000,
  "1 BHK Outside City Centre": 6000,
  "2 BHK in City Centre": 18000,
  "2 BHK Outside City Centre": 10000,
  "3 BHK in City Centre": 30000,
  "3 BHK Outside City Centre": 16000,
  "PG - Private Room (with meals)": 8000,
  "PG - Private Room (without meals)": 6000,
  "PG - Double Sharing (with meals)": 5500,
  "PG - Double Sharing (without meals)": 4000,
  "PG - Triple Sharing (with meals)": 4500,
  "PG - Triple Sharing (without meals)": 3000,
  "Gym Membership": 800,
  "Movie Ticket (Multiplex)": 170,
  "Netflix (Standard Plan)": 649,
  "Spotify Premium": 119,
  "Haircut (Men, basic salon)": 70,
  "Domestic Beer (pint, restaurant)": 160,
  "Imported Beer (bottle, restaurant)": 320,
};

// ============================================================
// CITY DEFINITIONS
// ============================================================

export const cities: CityData[] = [
  {
    name: "Mumbai",
    slug: "mumbai",
    state: "Maharashtra",
    description: "Financial capital of India, home to Bollywood and the busiest local train network in the world.",
    population: "2.1 Cr",
    image: "/cities/mumbai.webp",
    lastUpdated: "February 2026",
    contributors: 142,
    prices: createPrices(mumbaiPrices),
  },
  {
    name: "Delhi",
    slug: "delhi",
    state: "Delhi NCR",
    description: "National capital with a blend of historic monuments and modern infrastructure.",
    population: "1.9 Cr",
    image: "/cities/delhi.webp",
    lastUpdated: "February 2026",
    contributors: 128,
    prices: createPrices(delhiPrices),
  },
  {
    name: "Bangalore",
    slug: "bangalore",
    state: "Karnataka",
    description: "India's Silicon Valley and IT hub, known for pleasant weather and startup culture.",
    population: "1.3 Cr",
    image: "/cities/bangalore.webp",
    lastUpdated: "February 2026",
    contributors: 156,
    prices: createPrices(bangalorePrices),
  },
  {
    name: "Chennai",
    slug: "chennai",
    state: "Tamil Nadu",
    description: "Cultural capital of South India with a thriving auto and IT industry.",
    population: "1.1 Cr",
    image: "/cities/chennai.webp",
    lastUpdated: "February 2026",
    contributors: 89,
    prices: createPrices(chennaiPrices),
  },
  {
    name: "Hyderabad",
    slug: "hyderabad",
    state: "Telangana",
    description: "City of Pearls and Biryani, a growing IT and pharma hub.",
    population: "1.0 Cr",
    image: "/cities/hyderabad.webp",
    lastUpdated: "February 2026",
    contributors: 97,
    prices: createPrices(hyderabadPrices),
  },
  {
    name: "Pune",
    slug: "pune",
    state: "Maharashtra",
    description: "Oxford of the East with top educational institutions and a booming IT sector.",
    population: "72 L",
    image: "/cities/pune.webp",
    lastUpdated: "February 2026",
    contributors: 104,
    prices: createPrices(punePrices),
  },
  {
    name: "Kolkata",
    slug: "kolkata",
    state: "West Bengal",
    description: "City of Joy, known for its cultural heritage, sweets, and affordable living.",
    population: "1.5 Cr",
    image: "/cities/kolkata.webp",
    lastUpdated: "February 2026",
    contributors: 76,
    prices: createPrices(kolkataPrices),
  },
  {
    name: "Ahmedabad",
    slug: "ahmedabad",
    state: "Gujarat",
    description: "Textile city with a growing startup ecosystem and rich Gujarati food culture.",
    population: "83 L",
    image: "/cities/ahmedabad.webp",
    lastUpdated: "February 2026",
    contributors: 68,
    prices: createPrices(ahmedabadPrices),
  },
  {
    name: "Jaipur",
    slug: "jaipur",
    state: "Rajasthan",
    description: "The Pink City, famous for palaces, forts, and an affordable cost of living.",
    population: "40 L",
    image: "/cities/jaipur.webp",
    lastUpdated: "February 2026",
    contributors: 52,
    prices: createPrices(jaipurPrices),
  },
  {
    name: "Lucknow",
    slug: "lucknow",
    state: "Uttar Pradesh",
    description: "City of Nawabs, famous for its cuisine, tehzeeb, and rapidly growing infrastructure.",
    population: "37 L",
    image: "/cities/lucknow.webp",
    lastUpdated: "February 2026",
    contributors: 44,
    prices: createPrices(lucknowPrices),
  },
  ...additionalCities,
];

// ============================================================
// HELPER FUNCTIONS
// ============================================================

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return cities.map((c) => c.slug);
}

export function getPricesByCategory(prices: PriceItem[]): Record<string, PriceItem[]> {
  return prices.reduce(
    (acc, item) => {
      if (!acc[item.category]) acc[item.category] = [];
      acc[item.category].push(item);
      return acc;
    },
    {} as Record<string, PriceItem[]>
  );
}

export function calculateCostIndex(city: CityData): number {
  // Calculate a cost of living index relative to Mumbai (base = 100)
  const mumbai = cities.find((c) => c.slug === "mumbai");
  if (!mumbai || city.slug === "mumbai") return 100;

  const cityTotal = city.prices.reduce((sum, p) => sum + p.price, 0);
  const mumbaiTotal = mumbai.prices.reduce((sum, p) => sum + p.price, 0);

  return Math.round((cityTotal / mumbaiTotal) * 100);
}

const RENT_CATEGORIES = [
  "Accommodation - Rent (Monthly)",
  "PG / Shared Accommodation (Monthly)",
];

export function calculateRentIndex(city: CityData): number {
  const mumbai = cities.find((c) => c.slug === "mumbai");
  if (!mumbai || city.slug === "mumbai") return 100;

  const rentTotal = (c: CityData) =>
    c.prices
      .filter((p) => RENT_CATEGORIES.includes(p.category))
      .reduce((sum, p) => sum + p.price, 0);

  const cityRent = rentTotal(city);
  const mumbaiRent = rentTotal(mumbai);
  if (mumbaiRent === 0) return 0;

  return Math.round((cityRent / mumbaiRent) * 100);
}

export function formatPrice(price: number): string {
  if (price >= 100000) {
    return `₹${(price / 100000).toFixed(1)}L`;
  }
  return `₹${price.toLocaleString("en-IN")}`;
}

export function getPercentageDifference(price1: number, price2: number): number {
  if (price1 === 0) return 0;
  return Math.round(((price2 - price1) / price1) * 100 * 10) / 10;
}
